// Azure Functions v4 entry point
// This file imports all function modules to register them
import './functions/health';
import './functions/applications';
import './functions/upload';
import './functions/get-document-url';
import './functions/ab-test';
import './functions/track-ab-test';
import './functions/proxy-ab-test';
import './functions/dbvc';
import './functions/smoke-test';
import './functions/practitioner-dashboard';
import './functions/clinician-dashboard';
import './functions/list-practitioners';
import './functions/seed-database';
import './functions/store-booking-session';
import './functions/get-halaxy-availability';
import './functions/create-halaxy-booking';
import './functions/create-payment-intent';
import './functions/capture-payment';
import './functions/cancel-payment';
import './functions/halaxy-sync-timer';
import './functions/trigger-halaxy-sync';
import './functions/halaxy-api-discovery';
import './functions/debug-slots';
import './functions/fix-unix-timestamps';
import './functions/send-verification-code';
import './functions/verify-code';
import './functions/onboarding';
import './functions/process-booking-notification';
import './functions/accept-application';
import './functions/resend-onboarding';
import './functions/practitioners-admin';
import './functions/admin-reset-application';
import './functions/send-offer';
import './functions/accept-offer';
import './functions/upload-signed-contract';
import './functions/verify-halaxy-practitioner';

export * from './functions/health';
export * from './functions/applications';
export * from './functions/upload';
export * from './functions/get-document-url';
export * from './functions/ab-test';
export * from './functions/track-ab-test';
export * from './functions/smoke-test';
export * from './functions/practitioner-dashboard';
export * from './functions/seed-database';
export * from './functions/store-booking-session';
